---
distro: "pfsense"
version: "2.6.0"
guest_os_type: "FreeBSD_64"
packer_template: "pfsense.j2"
iso_checksum: "sha256:f6520bb14a5e690c6533e4e8fbf4a48d2967f3bc35a713e716b9c64317a13f23"
iso_location: "none"
iso_altlocation: "none"
iso_name: "pfSense-CE-2.6.0-RELEASE-amd64.iso"
install_file: "none"
templateks: "none"
iso:
  url: "https://nyifiles.netgate.com/mirror/downloads/pfSense-CE-2.6.0-RELEASE-amd64.iso.gz"
  alturl: "none"
  gzipped: true
  gzip_checksum: "sha256:941a68c7f20c4b635447cceda429a027f816bdb78d54b8252bb87abf1fc22ee3"
# packer:
#   template: "pfsense.j2"
#   guest_os_type: "FreeBSD_64"
