---
# zsh configuration
- name: Ensure {{ ansible_user_dir }}/.zprofile exists
  file:
    path: "{{ ansible_user_dir }}/.zprofile"
    state: touch
    access_time: preserve
    modification_time: preserve
    mode: '0644'
- name: Ensure directory for shell customizations exists
  file:
    path: "{{ ansible_user_dir }}/.zshrc.d"
    state: directory
    mode: '0755'
- name: Ensure ~/.zshrc.d/ files are sourced from .zprofile
  blockinfile:
    path: "{{ ansible_user_dir }}/.zprofile"
    marker: "# {mark}"
    marker_begin: "=== ANSIBLE MANAGED BLOCK BEGIN: Source files in .zshrc.d"
    marker_end: "END: .zshrc.d"
    block: |
      if [[ -d "$HOME/.zshrc.d" ]]; then
        source $HOME/.zshrc.d/*
      fi
#- name: Ensure shell customizations are installed
#  template:
#    src: ".zshrc.d/{{ item }}.j2"
#    dest: "{{ ansible_user_dir }}/.zshrc.d/{{ item }}"
#    mode: '0644'
#  with_items:
#  - '90user_bin_dir'
