---
# ==========================================================================
# Distribution specific overrides for default values in ../defaults/main.yml
# ==========================================================================
# defaults for GNS3
#gns3_version: "2.2.13"
#gns3_user_dir: "{{ ansible_user_dir }}/GNS3"
#gns3_config_dir: "{{ ansible_user_dir }}/.config/GNS3/2.2"

# ==========================================
# Additional distribution specific variables
# ==========================================
# defaults for GNS3
gns3_app: "/Applications/GNS3.app"
gns3_mac_plist: "{{ gns3_app }}/Contents/Info.plist"
gns3_mac_dmg: "GNS3-{{ gns3_version }}.dmg"
gns3_mac_dmg_url: "https://github.com/GNS3/gns3-gui/releases/download/v{{ gns3_version }}/{{ gns3_mac_dmg }}"
gns3_mac_dmg_checksum: "sha256:7925c7ae2d202b7b1a3e7f807e54a46c4da1a20fabc5c6201f77d01839454e74"
gns3_mac_dmg_mount_path: "/Volumes/GNS3 {{ gns3_version }}"
# Defaults for Wireshark
wireshark_version: "3.2.7"
wireshark_bin: "/usr/local/bin/wireshark"
wireshark_app: "/Applications/wireshark.app"
wireshark_mac_plist: "{{ wireshark_app }}/Contents/Info.plist"
wireshark_mac_dmg: "Wireshark%20{{ wireshark_version }}%20Intel%2064.dmg"
wireshark_mac_dmg_url: "https://1.na.dl.wireshark.org/osx/{{ wireshark_mac_dmg }}"
wireshark_mac_dmg_checksum: "sha256:1347138534c6d9adb2ee1af7898cac2248b63bfb1ac6afee54e17725ab333106"
wireshark_mac_dmg_mount_path: "/Volumes/Wireshark {{ wireshark_version }}"
#=====================
#  Homebrew packages
#=====================
system_brews: []
system_casks:
  - wireshark
dockitems_to_add:
  - name: GNS3
    path: "/Applications/GNS3.app"
