---
# tasks file for demoimage
- name: Empty the dock to just the terminal
  command: defaults write com.apple.dock persistent-apps -array '{
        GUID = 970228433;
        "tile-data" =         {
            book = <626f6f6b 04030000 00000410 30000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 24020000 0c000000 01010000 4170706c 69636174 696f6e73 09000000 01010000 5574696c 69746965 73000000 0c000000 01010000 5465726d 696e616c 2e617070 0c000000 01060000 04000000 18000000 2c000000 08000000 04030000 40000000 00000000 08000000 04030000 78ab0000 00000000 08000000 04030000 8ff60000 00000000 0c000000 01060000 54000000 64000000 74000000 08000000 00040000 41bbdb0a 35000000 18000000 01020000 02000000 00000000 0f000000 00000000 00000000 00000000 08000000 01090000 66696c65 3a2f2f2f 0c000000 01010000 4d616369 6e746f73 68204844 08000000 04030000 0020883d 3a000000 08000000 00040000 41bc6122 82000000 24000000 01010000 31384231 42453445 2d363944 342d3343 42452d38 3239342d 39343041 36413230 32323146 18000000 01020000 81000000 01000000 ef130000 01000000 00000000 00000000 01000000 01010000 2f000000 00000000 01050000 af000000 01020000 39653034 37653638 34333330 64306462 31306636 65613138 64643830 39613431 30376365 33316337 3b303030 30303030 303b3030 30303030 30303b30 30303030 30303030 30303030 3031613b 636f6d2e 6170706c 652e6170 702d7361 6e64626f 782e7265 61643b30 30303030 3030313b 30313030 30303033 3b303030 30303030 30303030 30663638 663b2f61 70706c69 63617469 6f6e732f 7574696c 69746965 732f7465 726d696e 616c2e61 70700000 a8000000 feffffff 01000000 00000000 0d000000 04100000 40000000 00000000 05100000 84000000 00000000 10100000 a8000000 00000000 40100000 98000000 00000000 02200000 58010000 00000000 05200000 c8000000 00000000 10200000 d8000000 00000000 11200000 0c010000 00000000 12200000 ec000000 00000000 13200000 fc000000 00000000 20200000 38010000 00000000 30200000 64010000 00000000 81f00000 6c010000 00000000>;
            "bundle-identifier" = "com.apple.Terminal";
            "dock-extra" = 0;
            "file-data" =             {
                "_CFURLString" = "file:///Applications/Utilities/Terminal.app/";
                "_CFURLStringType" = 15;
            };
            "file-label" = Terminal;
            "file-mod-date" = 3528491829;
            "file-type" = 41;
            "parent-mod-date" = 3537280502;
        };
        "tile-type" = "file-tile";
    }'
  notify: "Restart the Dock"
- name: Show percentage battery
  osx_defaults:
    domain: com.apple.menuextra.battery
    key: ShowPercentage
    type: bool
    value: true
    state: present

