---
# Create Kali-Linux-2016.2-vbox-amd64 basebox
- name: Download zip
  get_url:
    url: "https://images.offensive-security.com/virtual-images/Kali-Linux-2016.2-vbox-amd64.ova"
    dest: "{{ ansible_user_dir }}/Downloads/Kali-Linux-2016.2-vbox-amd64.ova"
    checksum: "sha1:a22978e7db5da82a6d013da51be227ee2982042d"
- name: Import the Kali appliance
  command: VBoxManage import {{ ansible_user_dir }}/Downloads/Kali-Linux-2016.2-vbox-amd64.ova
  args:
    creates: "{{ ansible_user_dir }}/VirtualBox VMs/Kali-Linux-2016.2-vbox-amd64"
- name: The following steps have to be completed manually before continuing.
  vars:
    msg: |
         login as root (password: toor)

           systemctl enable ssh
           useradd -b /home -U -m -s /bin/bash vagrant
           passwd vagrant
           su vagrant -c "mkdir -m 700 /home/vagrant/.ssh"
           echo 'vagrant	ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers.d/vagrant
           apt-get install -y aptitude

         Then, in the VM's settings, add a port forwarding rule from port 2201 on the localhost to
         port 22 on the guest and upload the public ssh key for the vagrant user with:

           scp -P 2201 ~/keys/vagrant.pub vagrant@localhost:/home/vagrant/.ssh/authorized_keys

  debug:
    msg: "{{ msg.split('\n') }}"
- pause:
    prompt: "Press Ctrl-C when you have completed the steps above."
- name: Delete any exiting .box file
  file:
    path: Kali-Linux-2016.2.box
    state: absent
- name: Package the base box
  command: vagrant package --base Kali-Linux-2016.2-vbox-amd64 --output Kali-Linux-2016.2.box
