---
# tasks file for packages
# Remove packages we don't want installed first
- name: Remove libreoffice
  apt: name=libreoffice-common state=absent purge=yes
  when: ansible_distribution == "Ubuntu"
  become: True
- name: Remove libreoffice styles
  apt: name=libreoffice-style-galaxy state=absent purge=yes
  when: ansible_distribution == "Ubuntu"
  become: True
- name: Remove firefox
  apt: name=firefox state=absent purge=yes
  when: ansible_distribution == "Ubuntu"
  become: True
- name: Remove firefox-locale-en
  apt: name=firefox-locale-en state=absent purge=yes
  when: ansible_distribution == "Ubuntu"
  become: True
- name: Remove unity-scope-firefoxbookmarks
  apt: name=unity-scope-firefoxbookmarks state=absent purge=yes
  when: ansible_distribution == "Ubuntu"
  become: True
# Install packages that DO NOT require a GUI
- name: Install vim with apt
  apt: name=vim state=present
  when: ansible_distribution == "Ubuntu"
  become: True
- name: Install screen with apt
  apt: name=screen state=present
  when: ansible_distribution == "Ubuntu"
  become: True
- name: Install tcpdump with apt
  apt: name=tcpdump state=present
  when: ansible_distribution == "Ubuntu"
  become: True
- name: Install traceroute with apt
  apt: name=traceroute state=present
  when: ansible_distribution == "Ubuntu"
  become: True
# Install packages that DO require a GUI
- name: Install chromium-browser
  apt: name=chromium-browser state=present
  when: ansible_distribution == "Ubuntu" and has_GUI == "yes"
  become: True
- name: Install nmap with apt
  apt: name=nmap state=present
  when: ansible_distribution == "Ubuntu" and has_GUI == "yes"
  become: True
- name: Install wireshark with apt
  apt: name=wireshark state=present
  when: ansible_distribution == "Ubuntu" and has_GUI == "yes"
  become: True
# Revmove packages installed as dependencies for packages we have removed
- name: Autoremove packages no longer needed
  command: apt-get -y autoremove
  when: ansible_distribution == "Ubuntu"
  become: True
