---
- name: Ensure apt cache is updated before installation
  apt:
    update_cache: yes
  become: yes
- name: Ensure system packages are installed
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ system_packages }}"
  become: yes
  when: system_packages is defined
