---
# The nmcli module is broken in ansible 2.4. This is supposedly fixed in
# the 2.5 devel branch.  https://github.com/ansible/ansible/pull/34577. I will
# revisit this when it is fixed in production.
#
- name: Ensure NetworkManager is started and enabled at boot
  service:
    name: NetworkManager
    state: started
    enabled: yes
  become: yes
- name: Check if libvirtd service is installed
  stat:
    path: /usr/lib/systemd/system/libvirtd.service
  register: libvirtd
  changed_when: False
- name: Ensure libvirtd is stopped and disabled at boot
  service:
    name: libvirtd
    state: stopped
    enabled: no
  become: yes
  when: libvirtd.stat.isreg is defined
#- name: Get a list of inactive default connections
#  shell: nmcli -t -f uuid,active c show | sed -n '/:no$/s/:no$//p'
#  register: inactive_connections
#  changed_when: False
#  become: root
#- name: Ensure any inactive connections are removed
#  command: nmcli c delete {{ item }}
#  loop: "{{ inactive_connections.stdout_lines }}"
#  become: yes
#  when: inactive_connections.stdout_lines|length > 0
- name: Get a list of active interfaces and associated connections
  command: nmcli -t -f device,uuid c show --active
  register: active_connections
  changed_when: False
  become: root
- name: Ensure active connections are named after their interfaces
  command: "nmcli c mod {{ item|regex_replace('^.*:','') }} connection.id {{ item|regex_replace(':.*$','') }}"
  become: yes
  loop: "{{ active_connections.stdout_lines }}"
- name: Ensure active connections have correct configuration
  command: nmcli c mod "{{ item.key }}" connection.autoconnect "{{ item.value.connection.autoconnect }}" connection.zone "{{ item.value.connection.zone }}" ipv4.method "{{ item.value.ipv4.method }}" ipv4.dns "{{ item.value.ipv4.dns }}" ipv4.addresses "{{ item.value.ipv4.addresses }}" ipv4.gateway "{{ item.value.ipv4.gateway }}" ipv4.ignore-auto-dns "{{ item.value.ipv4.ignore_auto_dns }}" ipv4.never-default "{{ item.value.ipv4.never_default }}" ipv6.method "{{ item.value.ipv6.method }}"
  become: yes
  with_dict: "{{ nmcon }}"
