---
# tasks file for caching-nameserver
- name: Install dnsmasq with apt
  apt: name=dnsmasq state=present
  when: ansible_distribution == "Ubuntu"
  become: True
- name: Configure interface for dnsmasq
    replace:
      dest=/etc/dnsmasq.conf
      regexp='^#interface=$'
      replace='interface=eth1'
  become: True
