---
# Default variables assumed to be the same for all platforms are commented out
# but you can override them here if you want to test new software versions
# one platform at a time.
virtualization: virtualbox
#==============
#  Packer
#==============
#packer_version: "1.6.2"
#packer_bin: "packer"
#packer_install_path: "/usr/local/bin"
packer_zip: "packer_{{ packer_version }}_darwin_amd64.zip"
packer_zip_url: "https://releases.hashicorp.com/packer/{{ packer_version }}/{{ packer_zip }}"
packer_zip_checksum: "sha256:2b5e8c76ae280c72fe33b2ac6511c24d2e0c02df9d437d2e4a5efbe988f71e2b"
#==============
#  Vagrant
#==============
#vagrant_version: "2.2.10"
#vagrant_bin: "vagrant"
vagrant_install_path: "/usr/local/bin"
vagrant_package: "vagrant_{{ vagrant_version }}_x86_64.dmg"
vagrant_package_url: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/{{ vagrant_package }}"
vagrant_package_checksum: "sha256:913d959455d37a0bb410c89ba3aedc886ccc76ce06bae7b228ba7454294325da"
vagrant_package_mount_path: "/Volumes/Vagrant"
#==============
#  Virtualbox
#==============
#virtualbox_short_version: "6.1"
#virtualbox_version: "6.1.14"
#virtualbox_build: "140239"
virtualbox_install_path: "/usr/local/bin"
virtualbox_package: "VirtualBox-{{ virtualbox_version }}-{{ virtualbox_build }}-OSX.dmg"
virtualbox_package_url: "http://download.virtualbox.org/virtualbox/{{ virtualbox_version }}/{{ virtualbox_package }}"
virtualbox_package_checksum: "sha256:3abeee4822707db2f949431391dba27827840aa5390a9ec4e1bafdc5c8c3aaaa"
virtualbox_package_mount_path: "/Volumes/VirtualBox"
#=====================
#  Homebrew packages
#=====================
system_brews:
  - dockutil
  - packer
  - packer-completion
  - vagrant-completion
system_casks:
  - google-chrome
  - vagrant
  # - virtualbox
dockitems_to_add:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
  - name: VirtualBox
    path: "/Applications/VirtualBox.app"
