---
supported_distributions:
  - MacOSX
  - Debian
download_dir: "{{ ansible_user_dir }}/Downloads"
packer_build_dir: "{{ ansible_user_dir }}/demo/ansible/packer"
key_dir: "{{ ansible_user_dir }}/keys"
virtualization: "virtualbox"
