---
- name: Get the current connection for the disabled interface
  command: nmcli -t -f GENERAL.CONNECTION device show {{ host_iface_netconfig_disabled }}
  register: iface_connection
  changed_when: false
- name: Ensure unconfigured connection is configured for practice
  command: "nmcli c mod {{ iface_connection.stdout | replace('GENERAL.CONNECTION:','') }} connection.id unconfigured connection.autoconnect no ipv4.addresses '10.1.1.1/24' ipv4.dns '' ipv4.gateway '' ipv4.never-default 'yes'"
  become: yes
- name: Copy exam files to root's homedir
  copy:
    dest: /root
    src: "{{ item }}"
  become: yes
  with_items:
    - exam1/README
- name: Lock the root user's password
  user:
    name: root
    password: '!'
  become: yes
- name: Ensure accounts for user and student do not exist
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  become: yes
  loop:
    - user
    - student

