---
- name: NFS services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - rpcbind
    - nfs-server
  become: yes
- name: Firewalld service
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - firewalld
  become: yes
- name: Ensure NFS is allowed through firewall on libvirt interfaces
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
    zone: libvirt
  with_items:
    - rpc-bind
    - mountd
    - nfs
  become: yes
- name: Ensure shared folders are exported
  ansible.builtin.copy:
    dest: /etc/exports.d/vagrant-shared-folders.exports
    content: "{{ ansible_user_dir }}/demo/rhcsa/labfiles 192.168.4.*(rw)"
    mode: '0644'
  become: yes
- name: Re-export shared folders
  ansible.builtin.command: exportfs -ra
  changed_when: false
  become: yes
