---
- name: Assert homebrew is installed
  ansible.builtin.assert:
    that: ansible_pkg_mgr == "homebrew"
    fail_msg: "A homebrew installation is required."
- name: Ensure system brews are installed
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ system_brews }}"
  when:
    - system_brews is defined
    - (system_brews | length > 0)
- name: Ensure system casks are installed
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ system_casks }}"
  when:
    - system_casks is defined
    - (system_casks | length > 0)
- name: Ensure icons are added to the Dock
  ansible.builtin.shell: dockutil --find '{{ item.name }}' || dockutil -v --add '{{ item.path }}' --no-restart
  register: dockadd
  changed_when: "'item added at end' in dockadd.stdout"
  loop: "{{ dockitems_to_add }}"
  notify: launcher-restart-macosx
# packer pre-requisite
- name: Ensure jmespath is installed for python3
  ansible.builtin.pip:
    name: jmespath
  become: true
