---
- name: Restart zebra daemon
  listen: restart_router
  community.general.runit:
    name: "zebra"
    state: restarted
  become: yes
- name: Restart OSPF daemon
  listen: restart_router
  community.general.runit:
    name: "ospfd"
    state: restarted
  become: yes
- name: Pause to allow time for OSPF routers to recalculate routes
  listen: wait_for_convergence
  ansible.builtin.pause:
    prompt: Playbook will continue in 60 seconds (unless you interrupt it)
    seconds: 60
  when: inventory_hostname_short != 'control'
