---
- name: Ensure runit service directories exist
  ansible.builtin.file:
    path: "/etc/sv/{{ service.name }}/log"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes
- name: Ensure runit log directory exists
  ansible.builtin.file:
    path: "/var/log/svlogd/{{ service.name }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes
- name: Ensure runit scripts for logging exist
  ansible.builtin.copy:
    content: |
      #!/bin/sh -euC
      svlogd -tt /var/log/svlogd/{{ service.name }}
    dest: "/etc/sv/{{ service.name }}/log/run"
    owner: root
    group: root
    mode: '0755'
  become: yes
- name: Ensure runit scripts for daemon exists
  ansible.builtin.template:
    src: runit_script.j2
    dest: "/etc/sv/{{ service.name }}/run"
    owner: root
    group: root
    mode: '0755'
  become: yes
- name: Enable {{ service.name }} daemon
  ansible.builtin.file:
    path: "/etc/service/{{ service.name }}"
    src: "/etc/sv/{{ service.name }}"
    state: link
  when: service.enabled
  become: yes
  notify: "{{ service.enablednotify | default(omit) }}"
- name: Wait for service lock file or socket
  ansible.builtin.wait_for:
    path: "{{ service.wait_for_file }}"
  when: service.wait_for_file is defined
