---
lab_net_type: ethernet
lab_net_autoconnect: yes
lab_net_zone: internal
lab_net_ipv4_method: manual
lab_net_ipv4_dns: "192.168.4.200"
lab_net_ipv4_gateway: "192.168.4.1"
lab_net_ipv4_ignore_auto_dns: yes
lab_net_ipv6_method: ignore
